host = ":8080"
[mysql]
connmaxlifetime = 60
maxidleconn = 60
maxopenconn = 10
addr = "127.0.0.1:3306"
name = "books"
user = "root"
pass = "password"

[redis]
addr = "127.0.0.1:6379"
db = "0"
maxretries = 5
minidleconns = 5
pass = ""
poolsize = 10